# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eaa91f1390a67f16e515b261c35e71c3383fcc58e2cbe44a9d93bef859b10d96b0a61ba61c82b078cba3c29bf428de847000af006140a96cd9fb07bae253d13e

test:
  secret_key_base: a52dce964458f30be0832ebc650a839ce1ea9e2a8c3bbec6385c211c16d424ed8a329273cf3bd601ed6f8d8520976eac615bb90b26e532b1558514b7680f8358

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
